version: '3'

services:
  db:
    container_name: backend-mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_DATABASE=blog
    ports:
      - '3307:3306'
    networks:
      - test
  api:
    container_name: blogimg
    image: blogimg
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - test
networks:
   test :
      external: true
